services:
  api-gateway:
    container_name: api-gateway
    image: alexfariakof/api-gateway:latest
    build:
      context: .
      dockerfile: ./src/api-gateway/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production
      CONSUL_HOST: consul
      SERVICE_DISCOVERY_URL: http://consul:8500      
    ports:
      - 4000:9000
    networks:
      - "gateway-net"

  categoria-service:
    container_name: categoria-service
    hostname: categoria-service
    image: alexfariakof/categoria-service:latest
    build:
      context: .
      dockerfile: ./src/BackEnd/Services/CategoriaService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  despesa-service:
    container_name: despesa-service
    hostname: despesa-service
    image: alexfariakof/despesa-service:latest
    build:
      context: .
      dockerfile: ./src/BackEnd/Services/DespesaService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production

  receita-service:
    container_name: receita-service
    hostname: receita-service
    image: alexfariakof/receita-service:latest
    build:
      context: .
      dockerfile: ./src/BackEnd/Services/ReceitaService/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Production

networks:
  gateway-net:
    driver: bridge
    name: "gateway-net"
