services:
  api-gateway:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_URLS: http://+:4000
      ASPNETCORE_HTTP_PORTS: 4000
    ports:
      - 4000:9000
    build:  
      context: .
      dockerfile: ./src/api-gateway/Dockerfile
    image: ${DOCKER_REGISTRY-}api-gateway  
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - gateway-net
    deploy:
      resources:
        limits:
          memory: 256M  
        reservations:
          memory: 128M 

  categoria-service:
    environment:      
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 9001
      ASPNETCORE_HTTPS_PORTS: 7001
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - gateway-net
    mac_address: 02:42:ac:11:00:02
    deploy:
      resources:
        limits:
          memory: 256M  
        reservations:
          memory: 128M 

  despesa-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - gateway-net
    mac_address: 02:42:ac:11:00:03
    deploy:
      resources:
        limits:
          memory: 256M  
        reservations:
          memory: 128M 

  receita-service:
    environment:
      ASPNETCORE_ENVIRONMENT: Development
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro
    networks:
      - gateway-net
    mac_address: 02:42:ac:11:00:04
    deploy:
      resources:
        limits:
          memory: 256M  
        reservations:
          memory: 128M 

  app-sts:
    image: ${DOCKER_REGISTRY-}sts
    build:
      context: .
      dockerfile: src/IdentityServer/Dockerfile
    environment:
      ASPNETCORE_ENVIRONMENT: Development
      ASPNETCORE_HTTP_PORTS: 8080
      ASPNETCORE_HTTPS_PORTS: 8081
    networks:
        - gateway-net    
    volumes:
      - ${APPDATA}/Microsoft/UserSecrets:/home/app/.microsoft/usersecrets:ro
      - ${APPDATA}/ASP.NET/Https:/home/app/.aspnet/https:ro    
    deploy:
      resources:
        limits:
          memory: 256M  
        reservations:
          memory: 128M


  consul:
    image: consul:1.15.4
    container_name: consul
    hostname: consul
    environment:
      - CONSUL_BIND_INTERFACE=eth0
    networks:
        - gateway-net
    ports:
       - 8500:8500
       - "8600:8600/udp"
    restart: always
    command: [
      "agent",
      "-server",
      "-ui",
      "-bootstrap-expect=1",
      "-client=0.0.0.0",
      "-bind=0.0.0.0"
    ]
    deploy:
      update_config:
        order: start-first 
      resources:
        limits:
          memory: 256M  
        reservations:
          memory: 128M

networks:
  gateway-net:
    driver: bridge
    name: "gateway-net"
